[project]
name = "jev-ticket-router"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ankit Kalluraya", email = "kallurayaankit@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "jevlang>=0.1.0",
    "python-dotenv>=1.2.3",
    "typesafe-sdk>=0.7.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
jev-ticket-router = "jev_ticket_router:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
